# Generated by Django 5.2.12 on 2026-09-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synapse', '0002_scanresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('INCONCLUSIVE', 'Inconclusive')], max_length=12),
        ),
    ]
