"""Turning what the person said into what the assistant says back.

Two things kept coming out wrong.

The assistant echoed a memory verbatim, so "remind me to take my tablets"
became "I'll remind you to take my tablets" - the assistant referring to its
own tablets. Anything quoted back has to be moved into the second person.

And the acknowledgement was generated by the router model, which at 1.5b
produced "Thank you for remembering to save that": the assistant thanking the
person for doing the assistant's job. Confirmations are short, predictable
sentences, so they are built here instead of asked for.

Lookarounds rather than \\b throughout, because these patterns survive being
edited by tools that mangle backslash escapes.
"""

import re

#: Applied before the single-word swaps, so "I am" becomes "you are" rather
#: than "you am".
_PHRASES = (
    (r"(?<![a-z'])i'm(?![a-z'])", "you're"),
    (r"(?<![a-z'])i've(?![a-z'])", "you've"),
    (r"(?<![a-z'])i'll(?![a-z'])", "you'll"),
    (r"(?<![a-z'])i'd(?![a-z'])", "you'd"),
    (r"(?<![a-z'])i am(?![a-z'])", "you are"),
    (r"(?<![a-z'])i was(?![a-z'])", "you were"),
    (r"(?<![a-z'])i have(?![a-z'])", "you have"),
    (r"(?<![a-z'])i had(?![a-z'])", "you had"),
)

_WORDS = {
    'i': 'you',
    'me': 'you',
    'my': 'your',
    'mine': 'yours',
    'myself': 'yourself',
}

_WORD_PATTERN = re.compile(
    r"(?<![a-z'])(" + '|'.join(sorted(_WORDS, key=len, reverse=True)) + r")(?![a-z'])",
    re.IGNORECASE,
)


def _match_case(original, replacement):
    if original.isupper() and len(original) > 1:
        return replacement.upper()
    if original[:1].isupper():
        return replacement[:1].upper() + replacement[1:]
    return replacement


def to_second_person(text):
    """Rewrite first-person wording as second person.

    "I left my keys on the table" -> "you left your keys on the table"
    "take my tablets"             -> "take your tablets"
    """
    if not text:
        return text

    result = text
    for pattern, replacement in _PHRASES:
        result = re.sub(
            pattern,
            lambda m, r=replacement: _match_case(m.group(0), r),
            result,
            flags=re.IGNORECASE,
        )
    return _WORD_PATTERN.sub(
        lambda m: _match_case(m.group(0), _WORDS[m.group(0).lower()]), result
    )


def _clean(text):
    return (text or '').strip().rstrip('.!').strip()


def acknowledge_memory(value):
    """Confirm that something has been remembered."""
    detail = _clean(to_second_person(value))
    if not detail:
        return "I'll remember that."
    return f"I'll remember that {detail[0].lower()}{detail[1:]}."


def confirm_reminder(task, spoken_time):
    """Confirm a reminder, in the person's terms rather than the assistant's."""
    detail = _clean(to_second_person(task))
    when = _clean(spoken_time)
    if not detail:
        return f"I'll remind you at {when}." if when else "I'll remind you."
    if not when:
        return f"I'll remind you to {detail}."
    return f"I'll remind you to {detail} at {when}."


def describe_reminder(task, spoken_time):
    """Read a pending reminder back."""
    detail = _clean(to_second_person(task))
    when = _clean(spoken_time)
    if not detail:
        return f"You have a reminder at {when}." if when else "You have a reminder set."
    if not when:
        return f"You asked me to remind you to {detail}."
    return f"You asked me to remind you to {detail} at {when}."


def answer_from_memory(memory_text):
    """Phrase a stored memory as an answer to a question about it."""
    detail = _clean(to_second_person(memory_text))
    if not detail:
        return "I don't have that written down yet."
    return f"{detail[0].upper()}{detail[1:]}."
