# Generated by Django 5.2.12 on 2026-09-21 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('text', models.TextField(help_text='What the person asked to be reminded about.')),
                ('spoken_time', models.CharField(blank=True, help_text='How the time was read back to them.', max_length=100)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['due_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='conversationturn',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='user_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='memoryrecord',
            name='user_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conversationturn',
            name='qwen_intent',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='conversationturn',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='voice.conversationsession'),
        ),
        migrations.AlterField(
            model_name='conversationturn',
            name='spoken_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='memoryrecord',
            index=models.Index(fields=['user_key', 'entity'], name='voice_memor_user_ke_cff979_idx'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voice.conversationsession'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['user_key', 'due_at'], name='voice_remin_user_ke_2709fe_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['delivered_at', 'due_at'], name='voice_remin_deliver_37221f_idx'),
        ),
    ]
